NDefines.NCountry.POLITICAL_POWER_LOWER_CAP = -9999.0
NDefines.NCountry.POLITICAL_POWER_UPPER_CAP = 9999.0
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 9999			
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 9999		
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 9999